services:
  mb:
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /dev/urandom:/dev/random:ro
    networks:
      - "databases"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: kF6qWvUISGgTdFD52G4e
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  databases:
    external: true
