version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=XJ06ueie
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=42usNJp3
      - MYSQL_DATABASE=keycloak
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
  mysql:
    external: true
