services:
  postgres:
    image: registry.paswolf.com/postgres:16-alpine-ssl
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=kF6qWvUISGgTdFD52G4e
      - POSTGRES_DB=paswolf_tf
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - database

volumes:
  postgres:
    external: true

networks:
  database:
    external: true
